### ISSUE TITLE
Example using the new YML syntax

### ISSUE THREAD

**Issue by RaduCStefanescu** [contention/rsync-deployments#2]
Hi, could you please provide an example about how to use rsync-deployments using the new YML syntax provided by Github Actions?

**Comment by thom4parisot** [comment]
I've proposed an attempt to do that in #7.

**Comment by pujianto** [comment]
- name: Deploy to Staging 
      uses: contention/rsync-deployments@v1.0.0
      env: 
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
      with: 
        args: "-avzr --delete --exclude .htaccess --exclude /uploads/ user@server.com:/srv/myapp/public/htdocs/"

**Comment by jonathanhatch** [comment]
I'm still getting docker exiting with code 2 when it gets to the entrypoint.sh. Any thoughts?

**Comment by volved-nl** [comment]
It seems to work here, I get a full list of all the files and this after:
sent 250663 bytes  received 56 bytes  167146.00 bytes/sec
total size is 37470734  speedup is 149.45

But no files appear at the receiving end. Any ideas what could cause this?

**Comment by generator85** [comment]
It seems to work here, I get a full list of all the files and this after:
```
sent 250663 bytes received 56 bytes 167146.00 bytes/sec
total size is 37470734 speedup is 149.45
```

But no files appear at the receiving end. Any ideas what could cause this?

**Comment by pujianto** [comment]
@generator85 Make sure your destination server:/path captured in $3 variable in [entrypoint.sh](https://github.com/contention/rsync-deployments/blob/65ac047ad677574a5795944766f6c5a9e958e53d/entrypoint.sh#L13)

**Comment by IlyaSemenov** [comment]
For whoever is landing up here, I recommend ditching the pre-made rsync actions and going either fully manually or use simpler helper like ssh-agent:

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Setup known_hosts
        run: echo 'my.host.io ssh-rsa AAAAB3....+8U=' >> ~/.ssh/known_hosts
      - name: Sync project files
        run: rsync -avzr --delete ${GITHUB_WORKSPACE}/ user@my.host.io:/srv/files/
```

(you can generate the line for known_host with ssh-keyscan, or simply copy it from your own `known_hosts`)

The reasons being:
1) Secure - you provide a specific SSH fingerprint, so the workflow will fail on MitM or DNS attacks (unlike this action, which runs with `-o StrictHostKeyChecking=no`)
2) Simpler - you have full control over the rsync command without having to remember which action args go where
