### ISSUE TITLE
Parameter Not Set

### ISSUE THREAD

**Issue by ShawnYcx** [contention/rsync-deployments#8]
Hi, I need some help! Not sure what i'm missing to make this action work.

<img width="986" alt="Screen Shot 2019-12-16 at 12 36 10 PM" src="https://user-images.githubusercontent.com/7292742/70933011-ac3d2a80-2000-11ea-856a-927291295b8d.png">

```
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: contention/rsync-deployments@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_TARGET_DIR }}
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
```

<img width="1572" alt="Screen Shot 2019-12-16 at 12 33 45 PM" src="https://user-images.githubusercontent.com/7292742/70932915-6ed89d00-2000-11ea-8365-0bd8aeb488d4.png">
